### ISSUE TITLE
NBA games from last nights didn't play

### ISSUE THREAD

**Issue by furkyto** [maxgalbu/xbmc.plugin.video.nba#76] opened 2018-03-23 06:04 UTC
I think that they put new encryption to all the game last night

**Comment by maliapac** [comment] 2018-03-23 22:49
Same problem here, any news or fix?

**Comment by mkorganashvili** [comment] 2018-03-24 17:14
stream type has changed

**Comment by maliapac** [comment] 2018-03-24 17:40
Is there any way to fix it?

**Comment by mkorganashvili** [comment] 2018-03-24 21:16
Stream is in mpd format now. For the quick research, not supported on kodi :(

**Comment by mkorganashvili** [comment] 2018-03-24 21:37
Leia is not coming out any time soon. And also mod is not supported yet. Hope they will add before release

**Comment by furkyto** [comment] 2018-03-24 22:06
What is leia ?

**Comment by dikri** [comment] 2018-03-24 22:12
Sister of Luke ;)

I don't know ist, but I think it is the new nickname of the next kodi release

**Comment by furkyto** [comment] 2018-03-24 22:12
yeah i see , thank you

**Comment by maliapac** [comment] 2018-03-24 22:14
We can only hope that the support for that format will be added in any of the next kodi releases.

**Comment by ivankokan** [comment] 2018-03-26 11:59
It should be possible to do it (https://github.com/peak3d/inputstream.adaptive), and I'm working on this - no guarantee I will make it. Please, don't comment things are not working anymore as we are all aware of it, and know what has changed.

**Comment by mkorganashvili** [comment] 2018-03-27 11:34
![image](https://user-images.githubusercontent.com/535431/37964930-4b0eebc0-31d4-11e8-9d38-47d127e360c9.png)
Yeah, just made it!

**Comment by ivankokan** [comment] 2018-03-27 11:38
@mkorganashvili I am very curious to see your commit (how far I am/was)!

**Comment by mkorganashvili** [comment] 2018-03-27 11:43
@ivankokan It will take time to finish the work. Just found the way to play mpd.

**Comment by furkyto** [comment] 2018-03-28 19:44
It give me imputstream.adaptive is missing on your install

**Comment by maliapac** [comment] 2018-03-28 20:50
Thank you for your effort. I really appreciate what you're trying to do @mkorganashvili. 

I've tried your install, but I still can't get the games to go. only condensed games work.

**Comment by mkorganashvili** [comment] 2018-03-28 21:03
@furkyto which version of kodi do you use?

@maliapac my pleasure ))
Can you post the log?

**Comment by maliapac** [comment] 2018-03-28 21:22
[kodi.log](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/1857815/kodi.log)
@mkorganashvili  - here is the log.

**Comment by cablegoon** [comment] 2018-03-28 21:46
Im getting the same error - condensed games work in SD

error below for the game 

5800224  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-4 part 2
23:15:48.124 T:2127558944   ERROR: EXCEPTION: XBMC is not playing any file
23:15:48.840 T:18446744071828928800  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
23:15:49.177 T:2127558944   ERROR: EXCEPTION: XBMC is not playing any file

**Comment by kuosu** [comment] 2018-03-28 22:20
Hi guys,
I also tried to run the latest fix, but without success. Kodi 17.6, Android 6.0.1 (sony tv). Before playing the game first time after installation, Kodi asked me to activate inputstream.adaptive. Anyway it failed moments later. Example part of my log is here: https://pastebin.com/t5bifTKy

**Comment by mkorganashvili** [comment] 2018-03-29 05:46
May be android has some problems, I'll check

**Comment by mkorganashvili** [comment] 2018-03-29 09:16
![screenshot_20180329-131325_chrome](https://user-images.githubusercontent.com/535431/38080722-48895ef0-3353-11e8-9b80-4681bb06df18.jpg)
Bad news for android users :/

**Comment by mkorganashvili** [comment] 2018-03-29 09:38
@maliapac or you can try nightly builds of k18.
You are welcome, I wish I could help you : )

**Comment by maliapac** [comment] 2018-03-29 10:41
@mkorganashvili I've just tried it on K18, it doesn't open the list of games so I don't know if decryption works. it gives me an error when I'm opening a list of games. Error: [Errno: 22]: Invalid argument

**Comment by mkorganashvili** [comment] 2018-03-29 11:06
@maliapac does release version work for old games?

**Comment by maliapac** [comment] 2018-03-29 11:32
@mkorganashvili if by release edition you mean nightly, no it doesn't. same error as yours. If you mean master's edition, I've just tried it. List does, it lists the games ok, but when I click to start the playback it seems like it will start, even a play sign on the top is shown, but then it stops with the "playback failed" message.

**Comment by furkyto** [comment] 2018-03-29 11:35
In kodi 18.0 with this release https://mirrors.kodi.tv/nightlies/windows/win64/master/ from 28.03 and your zip file of the nba plugin , the old game from past season start and the games from last night start too but the quality is bad and can't change it

**Comment by mkorganashvili** [comment] 2018-03-29 11:55
@maliapac I mean master. If there is problem with my version, then logs will be welcome : )

@furkyto quality is really poor, I guess there is problem with inputstream.adaptive plugin. I'll post the problem there.

**Comment by ThulsaD00M** [comment] 2018-03-29 13:30
@mkorganashvili 
Regarding the poor qualitiy: It´s right there...nothing is wrong with the inputstream.adaptive. It is just a problem in games.py. Archived games are not openend the way, as live-games are. I have just finished watching the Lakers-Mavericks game from last night in 720p (@29.97fps). All i had to do, is change the device clock (my device is a x86 machine running libreelec with kodi 17.6) back to 02:30 local time (Germany). By doing this, under Live Games within your pachted addon (i downloaded your .zip) the games from last night show up (again) and then i chosed the home/away feed. The Submenu then is to go live or start from the beginning. I selected start for beginning and the game just played fine!

You can try yourself. 

The Addon is simply erasing the live Games 4 hours after starting time. By changing the clock backwards, you can bring them back on!

Now, all you (ore someone else) have to do, is looking in the games.py and figure out, how the live-games (and the just finished games) are opened and paste this method to the archived games. I´m to stupid (it seems! :-)  )

Everthing will be fine then.

In case you still got problems with the qualitiy, you may have to set the inputstream.adaptive up the right way...i can help you guys!

**Comment by mkorganashvili** [comment] 2018-03-29 14:49
@ThulsaD00M there must be some coincidence. I can't really see the connection.

**Comment by mkorganashvili** [comment] 2018-03-29 14:51
![image](https://user-images.githubusercontent.com/535431/38095731-30a7b758-3382-11e8-9f25-3c345c340c07.png)

**Comment by mkorganashvili** [comment] 2018-03-29 16:46
Good news!
Quality problem was caused by 'UserAgent'. Server sends low qualities for mobile devices. Now I changed it with chrome's UserAgent and quality is good!

You can take last version of my code

**Comment by furkyto** [comment] 2018-03-29 17:03
Is there any way to make it with apple userAgent ?

**Comment by mkorganashvili** [comment] 2018-03-29 17:56
@furkyto kodi can not play format apple do.
is it important?

**Comment by mkorganashvili** [comment] 2018-03-29 19:26
I see.
They are planing to add support of SAMPLE-AES and we can use apple again.
For now maximum bandwidth is 4500kbps

**Comment by mkorganashvili** [comment] 2018-03-30 07:19
@maliapac addon has problem reading the settings. May be you should try to reinstall the addon

**Comment by jaydee73** [comment] 2018-03-30 13:12
Also runs on MAC OS X with K18 and the latest addon from mkorganashvili.

Anyone had luck with Android and K18? @maliapac: Any news?

**Comment by furkyto** [comment] 2018-03-30 14:41
@mkorganashvili can i ask you some questions on private ?

**Comment by mkorganashvili** [comment] 2018-03-30 14:48
@furkyto sure

**Comment by furkyto** [comment] 2018-03-30 16:53
where ? would you give me skype

**Comment by mkorganashvili** [comment] 2018-03-30 16:56
mkorganashvili is my skype : ))

**Comment by akulagr** [comment] 2018-03-31 16:18
Hello @mkorganasvili I've been testing the last version of your code on Android with K18. The problem that I'm having is that I get no picture whatsoever when I try to play a game (either live or archive). the stream starts but i only get audio and a black screen. I already fiddled around with video processing settings and inputstream adaptive settings to no avail. do you happen to have any suggestions to get this working?
appreciate the work you are doing keeping the add on running.

**Comment by mkorganashvili** [comment] 2018-03-31 22:25
Hello @akulagr. I'm guessing this is the problem of inputstream.adaptive. Maybe we should ask to them for the help

**Comment by furkyto** [comment] 2018-04-01 07:13
ffmpeg is not supported

**Comment by furkyto** [comment] 2018-04-01 10:37
@mkorganashvili i send you invitation in skype but you aren't accept yet :) , i'm furkyto on skype

**Comment by akulagr** [comment] 2018-04-01 11:31
@furkyto So that means there's no way to make it work on android with K18?

**Comment by mkorganashvili** [comment] 2018-04-01 15:33
It can be played, there must be a bug in the addon

**Comment by irandhal** [comment] 2018-04-04 07:13
same issue here, on android system (nvidia shield TV). Is there any chance to fix the issue before playoff ? the official NBA App for android TV sucks, and i really miss kodi's addon. How can i help ? (logs ? try kodi 18 ?)

**Comment by pi-iuselinux-lt** [comment] 2018-04-09 06:01
Does latest master still have stream quality issue? Tried changing quality settings does not have any effect. (Ubuntu 16.04.4 LTS,  Kodi 17.6). Should I change userAgent?

**Comment by mkorganashvili** [comment] 2018-04-10 12:36
@pi-iuselinux-lt userAgent is already changed. I had bed quality played only once and tried to stop and play the game again. it helped

**Comment by pi-iuselinux-lt** [comment] 2018-04-10 17:47
@mkorganashvili  Thanks, works like a charm on my laptop (Kodi 17.6, Ubuntu amd64), quality is much improved. For some reason, same version of Kodi is crashing on my Desktop, I will test RPI3 with OSMC latter.

**Comment by maxgalbu** [comment] 2018-04-10 21:34
Closing since @mkorganashvili fixed it. Download latest release from https://github.com/maxgalbu/xbmc.plugin.video.nba/releases

**Closed by maxgalbu** 2018-04-10 21:34 UTC
