### ISSUE TITLE
Problem logging in to the plugin

### ISSUE THREAD

**Issue by vishaldasari** [maxgalbu/xbmc.plugin.video.nba#55] opened 2017-10-02 03:28 UTC
I have a international league pass account and creds work on the website. However after entering it into add on, I am not able to play any game or archive. Highlights works fine though.

**Comment by justinro** [comment] 2017-10-02 23:05
Also having an issue playing any games - Have International LP, working perfect on the website.

Log File:
https://pastebin.com/raw/qRjJi7gD

**Comment by joeym2506** [comment] 2017-10-03 10:42
Also no longer working for me.

**Comment by dikri** [comment] 2017-10-03 16:47
Works for me, but I have to alter my username to my email address!

**Comment by suprabhatgurrala** [comment] 2017-10-03 16:56
I've tried both my username and email address but still not working. I'm getting an error similar to issue #46 , perhaps it's another agent issue?

**Comment by joeym2506** [comment] 2017-10-03 18:18
Also doesn't work as my email address. Have tried installing older versions and it still doesn't work.

**Comment by nzeppos** [comment] 2017-10-03 18:33
1.0.0 works fine with me, the only thing I had to change recently is to use the email address as a username. But this change applies to the official LP site as well, not just the addon.

**Comment by joeym2506** [comment] 2017-10-03 18:36
Is your account an international league pass?

**Comment by vishaldasari** [comment] 2017-10-04 01:42
hows it working for you? yes the username thing is true and I am using my email and its still not working.

**Comment by dikri** [comment] 2017-10-04 22:09
Its working for me, with international League Pass (I´m from Germany). Yesterday I watched two games with Kodi 17 on windows tablet, today I watched one game with my Amazon Fire TV (with Kodi 17). In both cases I have to Change my Username to my Email Adress. Because I changed my password in last playoffs on another device, I have to change it today and yesterday in both cases too.

**Comment by vishaldasari** [comment] 2017-10-05 00:08
I'm using India which is like 20 dollars for the whole year plus playoffs LOL. Might be a reason why its not working.

**Comment by dikri** [comment] 2017-10-05 00:11
No, I'm not sure where I bought it, but not in Germany ;)

**Comment by joeym2506** [comment] 2017-10-05 00:42
Does anybody have an alternative if this doesn't get fixed this season?

**Comment by handrewbrozel** [comment] 2017-10-05 05:07
It works with your email address only if your IP address is outside of the US. Something on NBA's end I guess is recognizing that your IP is not "International" and as a result won't let you login to international league pass. The only way I've gotten it to work is by using my email address in the username box and a VPN to an IP address outside of the US.

**Comment by itzeddie** [comment] 2017-10-07 12:43
Correct with the issue with email addresses, however further concern is a bunch of todays pre-season games are reporting no video URL.

**Comment by nzeppos** [comment] 2017-10-07 18:45
The no video URL error should be of no concern. The exact same games are not playing on the Xbox One official app either, so this must be an LP issue and not related to Max' addon.

**Comment by maxgalbu** [comment] 2017-10-08 17:21
Hi everyone, switching to email address as @dikri pointed out is the fix for this issue. Some of the games incorrectly report as viewable but they're not, I'm working on a fix.

**Comment by maxgalbu** [comment] 2017-10-09 13:13
Committted a fix for unplayable games: https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/ca6d71dac8fc2a7d8f73f53c54252fdf364316be

**Comment by justinro** [comment] 2017-10-09 19:44
I have my email address listed in the settings, and verified I can log-in to the International LP site to watch games, but still getting script errors when clicking on archived games:
https://pastebin.com/raw/sB8nBH1K

**Comment by maxgalbu** [comment] 2017-10-10 07:49
@Justinro what game were you trying to watch?

**Comment by Miss80** [comment] 2017-10-10 18:38
Same issue here. Changed userid into mailadress but still getting the url error. I tried several games in the archive for this week.

**Comment by justinro** [comment] 2017-10-10 19:16
@maxgalbu I was trying to watch the Warroirs vs Mavericks from Sunday, but I get the same error with any archived game. Here's a more complete log, along with screenshot showing that the LP website works for the same game:

https://pastebin.com/raw/r4ez8V51
https://imgur.com/a/99MB6

Thanks!

**Comment by dikri** [comment] 2017-10-10 22:10
So, I tried another view things, now I can confirm the problem. With Kodi 16.1, 17.1 and 17.4 I can not play all of the games, but on the website it works. The games that are not working, for example, are from 2017/10/08  sunday, maybe 07 saturday local american time. In germany these games are from sunday. 
-> MEL vs Thunder
-> Warriors vs Timberwolves
.....
Cavaliers vs Wizards and Knicks vs  Nets on this date are working without Problems. 

I don´t install the fix that max offers... because i don´t now how :)

**Comment by dikri** [comment] 2017-10-10 22:47
[kodi_not_playing.log](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/1373636/kodi_not_playing.log)
[kodi_playing.log](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/1373637/kodi_playing.log)
here are 2 logfiles. 
kodi_not_playing.log is the MELvsThunder game where i get the "can´t get video url". 
kodi_playing.log is the Cavs_vs_Wizard game that I can watch. 

00:31:33 T:5372  NOTICE: DVDPlayer: Opening:
vs
00:33:42 T:8056  NOTICE: DVDPlayer: Opening: http://nlds120.cdnak.neulion.com/nlds_vod/nba/vod/2017/10/08/11700040/87cf15/1_11700040_cle_was_2017_b_whole_1_6000_ipad.mp4.m3u8?hdnea=expires%3D1507674942%7Eaccess%3D%2Fnlds_vod%2Fnba%2Fvod%2F2017%2F10%2F08%2F11700040%2F87cf15%2F*%7Emd5%3Dc291a4b856ca067327089016a9035cc3&nltid=nba&nltdt=6&uid=2172066|User-Agent=iTunes-AppleTV/4.1

the Message "can´t get video url" seems to be right. But I don´t know why. Max, I hope this could be helpfull. Thanks for your effort.

**Comment by maxgalbu** [comment] 2017-10-10 22:49
The warriors-timberwolves (https://watch.nba.com/game/20171008/GSWMIN) - not mavericks - does not ALWAYS play on watch.nba.com too. If I play another video that I know it will start (eg: from https://watch.nba.com/game/20171008/CLEWAS), then click play again on GSWMIN, it works. So something is wrong with NBA website too. The fix I made was already tested with  GSWMIN of sunday, and it was working when i committed the fix. Let's see whether something changes, I'll keep testing against non-working games.

**Comment by dikri** [comment] 2017-10-10 22:59
yes, thats one reason why your plugin is awesome. great overview, simple as possible and the best video quality outside of apple products. (I think only on apple tv there is the 6000kbs option...thank you neulion...)

**Comment by maxgalbu** [comment] 2017-10-18 21:39
I've pushed version 1.0.1 to kodi's repo, closing this since the username -> email fixes this. For game issue let's continue on #60

**Closed by maxgalbu** 2017-10-18 21:39 UTC
